# Demo GRAHSP configuration
data_file = data/processed/catalog_demo.fits
column_list = jwst.nircam.F150W, jwst.nircam.F150W_err, jwst.nircam.F277W, jwst.nircam.F277W_err, jwst.nircam.F444W, jwst.nircam.F444W_err, jwst.miri.F770W, jwst.miri.F770W_err, HSC_i, HSC_i_err
